version: '3'

services:

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/app/lookback:/usr/src/app
    command: 'npx next dev'
    ports:
      - "8000:3000"

  database:
    container_name: database
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bash -c "tail -f log/development.log"
    # command: bash -c "rails s -b 0.0.0.0"
    volumes:
      - ./api:/myapp
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    depends_on:
      - database
    tty: true
    stdin_open: true

volumes:
  mysql_data: