default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  port: 3306

development:
  <<: *default
  host: database
  database: loolback_development
  password: password

test:
  <<: *default
  host: database
  database: loolback_test
  password: password

production:
  <<: *default
  database: myapp_prouction
  url: <%= Rails.application.credentials.production.database_url %>
