source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# 環境毎の設定管理を行う
gem "config"

# MySQLに接続する
gem "mysql2", "~> 0.5"

# pumaサーバーを使えるようにする（標準gem）
gem "puma", "~> 5.0"

# cors設定を管理する
gem "rack-cors"

# メールSDK
gem "resend", "~> 0.8.0"

# パスワードのハッシュ化と認証
gem "bcrypt", "~> 3.1.7"

# JWT
gem "jwt", "~> 2.7.0"

# クロスオリジンを許可
gem "rails_same_site_cookie", "~> 0.1.8"

# rails本体（標準gem）
gem "rails", "~> 7.0.4"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  # テストフレームワーク
  gem "rspec-rails"

  # rubocop(静的コード解析ツール) を使えるようにする。
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
